tests: Add tests 05-03 and 05-05
Signed-off-by: Mark Grant <m.grant.prg@gmail.com>

diff --git a/src/prg/tests/output-tests/test-05-05/test-05-05.sh.in b/src/prg/tests/output-tests/test-05-05/test-05-05.sh.in
--- a/src/prg/tests/output-tests/test-05-05/test-05-05.sh.in
+++ b/src/prg/tests/output-tests/test-05-05/test-05-05.sh.in
@@ -8,7 +8,9 @@ cd "$(dirname "$0")"
 
 where=$(( mge_basic_lib_output_where_stdout \
 	| mge_basic_lib_output_where_log ))
-when=$mge_basic_lib_output_when_silent
+when=$(( mge_basic_lib_output_when_quiet \
+	| mge_basic_lib_output_when_verbose ))
+
 
 test_name_digits=$(printf "%02d-%02d" "$where" "$when")
 
@@ -47,34 +49,26 @@ for ((verbosity = 0 ; verbosity <= 15 ; verbosity++)); do
 	mge_basic_lib_output "$msg" "$verbosity" "$where" "$when" \
 		1> test-"$test_name_digits"-stdout-result.txt \
 		2> test-"$test_name_digits"-stderr-result.txt
+	err=$?
+
+	# Should fail and exit 79 because when is 3, unless verbosity is silent
+	if (( verbosity != 0 )); then
+		if (( err != 79 )); then
+			exit 1
+		fi
+	fi
 
 	set -e
-
-	echo "$msg" > test-"$test_name_digits"-stdout-answer.txt
 
 	# allow logger/journal/syslog to flush
 	sleep 0.2
 
-	if _mge_basic_lib_is_bit_set "$when" "$verbosity"; then
-		cmp test-"$test_name_digits"-stdout-answer.txt \
-			test-"$test_name_digits"-stdout-result.txt
-		cmp test-"$test_name_digits"-stderr-answer.txt \
-			test-"$test_name_digits"-stderr-result.txt
-		if check_journal; then
-			continue
-		fi
-
-		if check_syslog; then
-			continue
-		fi
-	else
-		cmp test-"$test_name_digits"-a-stdout-answer.txt \
-			test-"$test_name_digits"-stdout-result.txt
-		cmp test-"$test_name_digits"-a-stderr-answer.txt \
-			test-"$test_name_digits"-stderr-result.txt
-		if ! check_journal && ! check_syslog; then
-			continue
-		fi
+	cmp test-"$test_name_digits"-stdout-answer.txt \
+		test-"$test_name_digits"-stdout-result.txt
+	cmp test-"$test_name_digits"-stderr-answer.txt \
+		test-"$test_name_digits"-stderr-result.txt
+	if ! check_journal && ! check_syslog; then
+		continue
 	fi
 
 	exit 1
